name: CI

on:
  push:
  schedule:
  - cron: '15 0 * * 5'
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    
    - uses: joshcarp/gogetcheck@v0.6.0

    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'

    - name: Make all
      run: make
